### ISSUE TITLE
500 error for some NYC events

### ISSUE THREAD

**Issue by cathydeng** [opencivicdata/api.opencivicdata.org#15]
there are server errors for some event pages (but not all) from the [nyc events listing](http://api.opencivicdata.org/events/?jurisdiction_id=ocd-jurisdiction/country:us/state:ny/place:new_york/government)

example: [ocd-event/001297df-b47c-40b2-a1b0-f31afb8082a1](http://api.opencivicdata.org/ocd-event/001297df-b47c-40b2-a1b0-f31afb8082a1/)(3rd event in the listing)

@mileswwatkins @rshorey 

(issue originally opened at https://github.com/opencivicdata/imago/issues/63)

**Comment by mileswwatkins** [comment]
Hmm, good question; at first glance I don't see a simple explanation. If you replicate the scrape locally, are those `event`s properly inserted into your OCD database?

**Comment by cathydeng** [comment]
pinging @fgregg

**Comment by fgregg** [comment]
I'm not exactly sure what you are asking @mileswwatkins ? 

You mean like:

```
nyc (scrape, import, report)
  events: {}
events scrape:
  duration:  0:44:26.663293
  objects:
    event: 10000
jurisdiction scrape:
  duration:  0:00:00.135233
  objects:
    jurisdiction: 1
    organization: 4
    post: 51
import:
  event: 10000 new 0 updated 0 noop
  jurisdiction: 0 new 0 updated 1 noop
  organization: 0 new 0 updated 4 noop
  post: 0 new 0 updated 51 noop
```

**Comment by mileswwatkins** [comment]
Hmm, what I'm essentially asking is whether the `event`s that are breaking are ones that are still being imported each night, or whether they could be weird old data that's junk anyway and we should remove. Does that make sense?

**Comment by fgregg** [comment]
I'm not sure. From our point of view it would be safe for you to delete all
the events and have the scrapers repopulate.

On Thu, Sep 10, 2015 at 3:40 PM, Miles Watkins <notifications@github.com>
wrote:

> Hmm, what I'm essentially asking is whether the events that are breaking
> are ones that are still being imported each night, or whether they could be
> weird old data that's junk anyway and we should remove. Does that make
> sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/api.opencivicdata.org/issues/15#issuecomment-139372762>
> .
>



-- 
773.888.2718

**Comment by mileswwatkins** [comment]
Cool, that would be fine with us. Can you guys write the `event`-clearing code that we can execute on the database, in the same way you did for `committee`s with @rshorey?

**Comment by jpmckinney** [comment]
Closing as the API at this URL is gone.
